<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example.manhunt</groupId>
    <artifactId>Manhunt-Parent</artifactId>
    <version>1.1</version>
    <packaging>pom</packaging>

    <modules>
        <module>core</module>
        <module>bukkit</module>
        <module>sponge</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>25</java.version>
        <spigot.version>1.21.1-R0.1-SNAPSHOT</spigot.version>
        <sponge.version>8.0.0</sponge.version>
    </properties>

    <profiles>
        <profile>
            <id>v1_21</id>
            <properties>
                <version.tag>1.21.x</version.tag>
                <spigot.version>1.21.1-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>12.0.0-SNAPSHOT</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_20</id>
            <properties>
                <version.tag>1.20.x</version.tag>
                <spigot.version>1.20.1-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>10.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_19</id>
            <properties>
                <version.tag>1.19.x</version.tag>
                <spigot.version>1.19.4-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>10.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_18</id>
            <properties>
                <version.tag>1.18.x</version.tag>
                <spigot.version>1.18.2-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>9.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_17</id>
            <properties>
                <version.tag>1.17.x</version.tag>
                <spigot.version>1.17.1-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>8.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_16</id>
            <properties>
                <version.tag>1.16.x</version.tag>
                <spigot.version>1.16.5-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>8.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_15</id>
            <properties>
                <version.tag>1.15.x</version.tag>
                <spigot.version>1.15.2-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>8.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_14</id>
            <properties>
                <version.tag>1.14.x</version.tag>
                <spigot.version>1.14.4-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>8.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_13</id>
            <properties>
                <version.tag>1.13.x</version.tag>
                <spigot.version>1.13.2-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>8.0.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_12</id>
            <properties>
                <version.tag>1.12.x</version.tag>
                <spigot.version>1.12.2-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>7.3.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_11</id>
            <properties>
                <version.tag>1.11.x</version.tag>
                <spigot.version>1.11.2-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>7.3.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_10</id>
            <properties>
                <version.tag>1.10.x</version.tag>
                <spigot.version>1.10.2-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>7.3.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_9</id>
            <properties>
                <version.tag>1.9.x</version.tag>
                <spigot.version>1.9.4-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>7.3.0</sponge.version>
            </properties>
        </profile>
        <profile>
            <id>v1_8</id>
            <properties>
                <version.tag>1.8.x</version.tag>
                <spigot.version>1.8.8-R0.1-SNAPSHOT</spigot.version>
                <sponge.version>7.3.0</sponge.version>
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>24.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
